
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthWindCoreLibrary.Data.Configurations;
using NorthWindCoreLibrary.Models;
using System;
using Microsoft.Extensions.Configuration;

#nullable disable

namespace NorthWindCoreLibrary.Data
{
    public partial class Context : DbContext
    {
        public Context()
        {
        }

        public Context(DbContextOptions<Context> options)
            : base(options)
        {
        }

        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                StandardConnection(optionsBuilder);
            }
        }
        /// <summary>
        /// Configure for simple connection
        /// </summary>
        /// <param name="optionsBuilder"></param>
        private static void StandardConnection(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = ReadAppsettings(out var _ ).GetConnectionString("DatabaseConnection");

            if (Environment.UserName != "PayneK")
            {
                connectionString = connectionString.Replace("4", "");
            }

            optionsBuilder.UseSqlServer(connectionString);
        }
        /// <summary>
        /// Read connection string from appsettings.json
        /// </summary>
        /// <param name="builder"></param>
        /// <returns>Connection string</returns>
        /// <remarks>
        /// Next level (which I have coded) is to have three environment which can
        /// come from one or more appsettings files along with setting the environment
        /// via Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") for ASP.NET Core
        /// or a custom variable e.g. Environment.GetEnvironmentVariable("OED_ENVIRONMENT")
        /// </remarks>
        private static IConfigurationRoot ReadAppsettings(out IConfigurationBuilder builder)
        {
            builder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            IConfigurationRoot config = builder.Build();


            return config; // connection string
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ContactTypeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CustomersConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
